task/urls.py
from django.urls import path

from task import views

urlpatterns = [
    path('', views.tasks, name='tasks'),
    # path('scripts/', views.scripts, name='scripts'),
    path('add_employee/', views.add_employee, name='add_employee'),
    path('inbox/add_employee/', views.add_employee, name='add_employee'),
    path('outbox/add_employee/', views.add_employee, name='add_employee'),
    path('archive/add_employee/', views.add_employee, name='add_employee'),
    path('add_task/', views.add_task, name='add_task'),
    path('validate_task_name/', views.validate_task_name, name='validate_task_name'),
    path('validate_description/', views.validate_description, name='validate_description'),
    path('validate_message/', views.validate_message, name='validate_message'),
    path('inbox/', views.tasks_inbox, name='tasks_inbox'),
    path('outbox/', views.tasks_outbox, name='tasks_outbox'),
    path('archive/', views.tasks_archive, name='tasks_archive'),
    path('download/<int:file_id>/', views.download_file, name='download_file'),
    path('download_file_answer/<int:file_id>/', views.download_file_answer, name='download_file_answer'),
    path('complete/', views.complete_task, name='complete_task'),
    path('rejected/', views.reject_task, name='reject_task'),
    path('accept/<int:task_id>/', views.accept_task, name='accept_task'),
    path('archive/<int:task_id>/', views.archive_task, name='archive_task'),
    path('delete/<int:task_id>/', views.delete_task, name='delete_task'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('tasks/', include('task.urls')),
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
]

task/models.py
import datetime
from datetime import date

from django.db import models

from task_manager import settings
from user.models import User


# Create your models here.

class Task(models.Model):
    users = models.ManyToManyField(User, through='UserTask')
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=1000, null=True, blank=True)
    date_start = models.DateField()
    date_end = models.DateField(blank=True, null=True)
    initiator = models.CharField(max_length=60, blank=True, null=True)
    message = models.TextField(max_length=1000, blank=True, null=True)
    priority = models.ForeignKey('Priority', on_delete=models.PROTECT)

    def __str__(self):
        return self.name + " " + self.description

    @staticmethod
    def find_task_by_id(task_id: int) -> 'Task' or None:
        task = Task.objects.filter(id=task_id)
        if task:
            return task[0]
        return None

    def add_date_end(self, date_end: 'date') -> None:
        self.date_end = date_end

    def add_priority(self, priority: 'Priority') -> None:
        self.priority_id = priority.id


class Priority(models.Model):
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'
    PRIORITY_CHOICES = [
        (LOW, 'Низкий'),
        (MEDIUM, 'Средний'),
        (HIGH, 'Высокий'),
    ]
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default=LOW)

    @staticmethod
    def get_or_create(priority: str) -> 'Priority':
        return Priority.objects.get_or_create(priority=priority)[0]

    def __str__(self):
        return str(self.priority)


class Status(models.Model):
    INBOX = 'inbox'  # входящие задачи
    OUTBOX = 'outbox'  # исходящие задачи
    COMPLETED = 'completed'  # заверщенные задачи
    FAILED = 'failed'  # просроченные
    REJECTED = 'rejected'  # отклоненные
    ACCEPTED = 'accepted'  # принятые
    ARCHIVED = 'archived'  # архивные
    STATUS_CHOICES = (
        (INBOX, 'Inbox'),
        (OUTBOX, 'Outbox'),
        (COMPLETED, 'Completed'),
        (FAILED, 'Failed'),
        (REJECTED, 'Rejected'),
        (ACCEPTED, 'Accepted'),
        (ARCHIVED, 'Archived'),
    )
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default=INBOX)

    @staticmethod
    def create(status: str) -> 'Status':
        status = Status(status=status)
        status.save()
        return status

    def __str__(self):
        return self.status


class UserTask(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    status = models.OneToOneField(Status, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user) + " " + str(self.task) + " " + str(self.status)

    @staticmethod
    def create_user_task(user: 'User', task: 'Task', status: 'Status') -> None:
        user_task = UserTask.objects.create(user=user, task=task, status=status)
        user_task.save()

    @staticmethod
    def find_usertasks_by_statuses(task_id: int, statuses: [str]) -> 'UserTask' or None:
        usertasks = UserTask.objects.filter(task_id=task_id, status__status__in=statuses).all()
        print(f'usertasks изметода: {usertasks}')
        if usertasks:
            return usertasks
        return None

    @staticmethod
    def __get_count_tasks(user_id: int, statuses: [str]) -> int:
        return UserTask.objects.filter(status__status__in=statuses, user_id=user_id).distinct('task').count()

    @staticmethod
    def count_tasks(user_id: int) -> int:
        return UserTask.__get_count_tasks(user_id, [Status.ACCEPTED, Status.FAILED])

    @staticmethod
    def count_inbox_tasks(user_id: int) -> int:
        return UserTask.__get_count_tasks(user_id, [Status.INBOX])

    @staticmethod
    def count_outbox_tasks(user_id: int) -> int:
        return UserTask.__get_count_tasks(user_id, [Status.OUTBOX, Status.COMPLETED,
                                                    Status.FAILED, Status.ACCEPTED,
                                                    Status.REJECTED])

    @staticmethod
    def find_usertask_by_user_id_and_statuses(user_id: int, statuses: [str]) -> 'UserTask':
        usertasks = (
            UserTask.objects.filter(user_id=user_id, status__status__in=statuses).distinct('task').all().order_by(
                'task', '-task__date_start'))
        if Status.FAILED in statuses:
            for usertask in usertasks:
                if usertask.task.date_end:
                    if usertask.task.date_end < datetime.date.today():
                        usertask.status.status = Status.FAILED
                        usertask.status.save()
        return usertasks


class File(models.Model):
    task = models.ForeignKey(to=Task, on_delete=models.CASCADE, null=True)
    file = models.FileField(upload_to='files/', null=True, blank=True)

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def __str__(self):
        return str(self.file)

    @staticmethod
    def create_and_save_file(file: 'File') -> 'File':
        file = File(file=file)
        file.save()
        return file

    def add_task(self, task: 'Task') -> None:
        self.task_id = task.id
        self.save()

    @staticmethod
    def find_file_by_id(file_id: int) -> 'File' or None:
        file = File.objects.filter(id=file_id)
        if file:
            return file[0]
        return None

    @staticmethod
    def find_file_by_id_task(task_id: int) -> 'File' or None:
        file = File.objects.filter(task_id=task_id)
        if file:
            return file[0]
        return None


class FileAnswer(models.Model):
    task = models.ForeignKey(to=Task, on_delete=models.CASCADE, null=True)
    file_answer = models.FileField(upload_to='files_answer/', null=True, blank=True)

    def delete(self, *args, **kwargs):
        self.file_answer.delete()
        super().delete(*args, **kwargs)

    def __str__(self):
        return str(self.file_answer)

    @staticmethod
    def create_and_save_file(file: 'FileAnswer') -> 'FileAnswer':
        file_answer = FileAnswer(file_answer=file)
        file_answer.save()
        return file_answer

    def add_task(self, task: 'Task') -> None:
        self.task_id = task.id
        self.save()

    @staticmethod
    def find_file_by_id(file_id: int) -> 'FileAnswer' or None:
        file = FileAnswer.objects.filter(id=file_id)
        if file:
            return file[0]
        return None

    @staticmethod
    def find_file_by_id_task(task_id: int) -> 'File' or None:
        file_answer = FileAnswer.objects.filter(task_id=task_id)
        if file_answer:
            return file_answer[0]
        return None

task/forms.py
from datetime import datetime, date

from django import forms
from django.forms import ModelForm, Form
from task.models import Priority, Task, File


class TaskForm(ModelForm):
    name = forms.CharField(label='Наименование задачи', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'text', 'placeholder': 'Наименование задачи'}))
    date_end = forms.DateField(label='Deadline', required=False,
                               widget=forms.DateInput(attrs={'type': 'date', 'class': 'datepicker form-control'}),
                               initial=date.today())
    description = forms.CharField(label='Описание (необязательно)', required=False, widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Описание (необязательно)', 'style': 'height: 250px;'}))

    class Meta:
        model = Task
        fields = ['name', 'date_end', 'description']

    def __init__(self, user_login, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['executors'] = forms.CharField(label='Исполнитель',
                                                   widget=forms.Select(choices=user_login.get_employees_for_choice(),
                                                                       attrs={'class': 'form-select',
                                                                              'aria-label': ''}))


#     name = forms.CharField(label='Name', max_length=50)
#     description = forms.CharField(widget=forms.Textarea, max_length=1000)
#     deadline = forms.DateField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'date'}))
#     priority = forms.ChoiceField(choices=Priority.PRIORITY_CHOICES)
#     executors = forms.CharField(widget=forms.Select(choices=User.get_user_choices()))


class PriorityForm(ModelForm):
    priority = forms.ChoiceField(label='Приоритет', choices=Priority.PRIORITY_CHOICES,
                                 widget=forms.Select(attrs={'class': 'form-select', 'aria-label': ''}))

    class Meta:
        model = Priority
        fields = ['priority']


class FileForm(ModelForm):
    file = forms.FileField(label='Загрузка', required=False,
                           widget=forms.FileInput(attrs={'class': 'form-control', 'type': 'file'}))

    class Meta:
        model = File
        fields = ['file']

# Это не работает
# class FileForm(forms.Form):
#     file = forms.FileField(widget=forms.ClearableFileInput(attrs={'allow_multiple_selected': True}))


# Для загрузки нескольких файлов создаем несколько классов
# class MultipleFileInput(forms.ClearableFileInput):
#     allow_multiple_selected = True
#
#
# class MultipleFileField(forms.FileField):
#     def __init__(self, *args, **kwargs):
#         kwargs.setdefault("widget", MultipleFileInput())
#         super().__init__(*args, **kwargs)
#
#     def clean(self, data, initial=None):
#         single_file_clean = super().clean
#         if isinstance(data, (list, tuple)):
#             result = [single_file_clean(d, initial) for d in data]
#         else:
#             result = single_file_clean(data, initial)
#         return result
#
#
# class FileFieldForm(forms.Form):
#     file_field = MultipleFileField()

task/templates/utils/addTask.html
<div class="col">
    <div class="card border-secondary h-100" style="max-width: 18rem; ">
{#        <a class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal"#}
{#           style="width: 100%; height: 100%; font-size: 30px" href="">Добавить задачу</a>#}
        <button
                type="button"
                class="btn btn-outline-secondary"
                data-bs-toggle="modal"
                data-bs-target="#ModalAdd"
                style="width: 100%; height: 100%; font-size: 30px; min-height: 150px;"
        >
            Добавить задачу
        </button>
    </div>
</div>
{#style="padding-top: 50%; padding-bottom: 50%; font-size: 30px"#}
<!-- Модальное окно -->
<div
        class="modal fade"
        id="ModalAdd"
        tabindex="-1"
        aria-labelledby="modalLabel"
        aria-hidden="true"
>
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modalLabel">
                    Добавить задачу
                </h1>

                <button
                        type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Закрыть"
                ></button>
            </div>
            <div class="modal-body">

                <form method="post" id="addTask" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        {{ taskForm.name }}
                        <label for="{{ taskForm.name.id_for_label }}">{{ taskForm.name.label }}</label>
                    </div>

                    <div class="row g-2 mb-3">
                        <div class="col-md">
                            <label for="{{ taskForm.executors.id_for_label }}"
                                   class="mb-2">{{ taskForm.executors.label }}</label>
                            {{ taskForm.executors }}

                        </div>
                        <div class="col-md">
                            <label for="{{ priorityForm.priority.id_for_label }}"
                                   class="mb-2">{{ priorityForm.priority.label }}</label>
                            {{ priorityForm.priority }}
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ taskForm.date_end.id_for_label }}"
                               class="mb-2">{{ taskForm.date_end.label }}</label>
                        {{ taskForm.date_end }}
                    </div>
                    <div class="form-floating mb-3">
                        {{ taskForm.description }}
                        <label for="{{ taskForm.description.id_for_label }}">{{ taskForm.description.label }}</label>
                    </div>
                    <div class="input-group mb-3">
                        <label class="input-group-text"
                               for="{{ fileForm.file.id_for_label }}">{{ fileForm.file.label }}</label>
                        {{ fileForm.file }}
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button
                        type="button"
                        class="btn btn-secondary"
                        data-bs-dismiss="modal"
                >
                    Закрыть
                </button>
                <button type="submit" form="addTask" class="btn btn-primary" id="btn-addTask">
                    Отправить
                </button>
            </div>
        </div>
    </div>
</div>

task/templates/utils/add_task.html
<div class="col">
    <div class="card border-secondary h-100" style="max-width: 18rem; ">
{#        <a class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal"#}
{#           style="width: 100%; height: 100%; font-size: 30px" href="">Добавить задачу</a>#}
        <button
                type="button"
                class="btn btn-outline-secondary"
                data-bs-toggle="modal"
                data-bs-target="#ModalAdd"
                style="width: 100%; height: 100%; font-size: 30px; min-height: 150px;"
        >
            Добавить задачу
        </button>
    </div>
</div>
{#style="padding-top: 50%; padding-bottom: 50%; font-size: 30px"#}
<!-- Модальное окно -->
<div
        class="modal fade"
        id="ModalAdd"
        tabindex="-1"
        aria-labelledby="modalLabel"
        aria-hidden="true"
>
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modalLabel">
                    Добавить задачу
                </h1>

                <button
                        type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Закрыть"
                ></button>
            </div>
            <div class="modal-body">

                <form method="post" id="addTask" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        {{ taskForm.name }}
                        <label for="{{ taskForm.name.id_for_label }}">{{ taskForm.name.label }}</label>
                    </div>

                    <div class="row g-2 mb-3">
                        <div class="col-md">
                            <label for="{{ taskForm.executors.id_for_label }}"
                                   class="mb-2">{{ taskForm.executors.label }}</label>
                            {{ taskForm.executors }}

                        </div>
                        <div class="col-md">
                            <label for="{{ priorityForm.priority.id_for_label }}"
                                   class="mb-2">{{ priorityForm.priority.label }}</label>
                            {{ priorityForm.priority }}
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ taskForm.date_end.id_for_label }}"
                               class="mb-2">{{ taskForm.date_end.label }}</label>
                        {{ taskForm.date_end }}
                    </div>
                    <div class="form-floating mb-3">
                        {{ taskForm.description }}
                        <label for="{{ taskForm.description.id_for_label }}">{{ taskForm.description.label }}</label>
                    </div>
                    <div class="input-group mb-3">
                        <label class="input-group-text"
                               for="{{ fileForm.file.id_for_label }}">{{ fileForm.file.label }}</label>
                        {{ fileForm.file }}
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button
                        type="button"
                        class="btn btn-secondary"
                        data-bs-dismiss="modal"
                >
                    Закрыть
                </button>
                <button type="submit" form="addTask" class="btn btn-primary" id="btn-addTask">
                    Отправить
                </button>
            </div>
        </div>
    </div>
</div>

task/templates/utils/button.html
<a href="
    {% if url == '#' %}
    #
    {% elif url == 'accept' %}
    {% url 'accept_task' usertask.task.id %}
    {% elif url == 'archive' %}
    {% url 'archive_task' usertask.task.id %}
    {% elif url == 'delete' %}
    {% url 'delete_task' usertask.task.id %}
    {% endif %}
"
   class="btn {% include 'utils/class_status.html' with class='btn-outline' %}"
        {% if is_modal == 'true' %}
   data-bs-toggle="modal"
   data-bs-target="#MessageModal{{ usertask.task.id }}"
        {% endif %}
>{{ text_button }}</a>

task/templates/utils/class_status.html
{% if usertask.status.status == 'inbox' %}
    {{ class }}-info
{% elif usertask.status.status == 'outbox' %}
    {{ class }}-info
{% elif usertask.status.status == 'completed' %}
    {{ class }}-success
{% elif usertask.status.status == 'failed' %}
    {{ class }}-danger
{% elif usertask.status.status == 'rejected' %}
    {{ class }}-dark
{% elif usertask.status.status == 'accepted' %}
    {{ class }}-primary
{% elif usertask.status.status == 'archived' %}
    {{ class }}-secondary
{% endif %}

task/templates/utils/message.html
<!-- Modal -->
<div class="modal fade" id="MessageModal{{ usertask.task.id }}" tabindex="-1" aria-labelledby="ModalLabelMessage"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabelMessage">Сообщение</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" id="addMessage{{ usertask.task.id }}" action="
                {% if url == 'complete' %}
                {% url 'complete_task' %}
                {% elif url == 'reject' %}
                {% url 'reject_task' %}
                {% endif %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="text" name="task_id" value="{{ usertask.task.id }}" hidden="hidden">
                    <div class="form-floating mb-3">
                        <textarea name="message" cols="40" rows="10" class="form-control"
                                  placeholder="Сообщение (необязательно)" style="height: 150px;"
                                  id="id_message"></textarea>
                        <label for="id_message">Сообщение (необязательно)</label>
                    </div>
                    <div class="input-group mb-3">
                        <label class="input-group-text" for="id_file">Загрузка</label>
                        <input type="file" name="file_answer" class="form-control" id="id_file">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <button type="submit" class="btn btn-primary" form="addMessage{{ usertask.task.id }}" id="btn-complete">
                    Завершить
                </button>
            </div>
        </div>
    </div>
</div>